### ISSUE TITLE
运行之后内容修改不生效？

### ISSUE THREAD

**Issue by comalan** [henter/ReactNativeRubyChina#2]
下载了之后运行，修改页面内容不生效，请问如何处理呢？

**Comment by henter** [comment]
Hi,
你好，修改一下Appdelegate.m，把里面第二个jsCodeLocation注视掉

Sent from Outlook

On Fri, Aug 28, 2015 at 5:48 AM -0700, "comalan" notifications@github.com wrote:

下载了之后运行，修改页面内容不生效，请问如何处理呢？
