### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by ZXSGG** [henter/ReactNativeRubyChina#3]
缺少rootViewController头文件和实现文件

**Comment by henter** [comment]
@cheniuiOSloved 
运行 `npm install`
然后重新打开xcode再编译

**Comment by penguin1214** [comment]
建议在README中添加`在项目根目录下执行 npm install`。

**Comment by henter** [comment]
@penguin-penpen 嗯 前面已经加到README了。
谢谢反馈。
