### ISSUE TITLE
Could not connect to development server.

### ISSUE THREAD

**Issue by zp0708** [henter/ReactNativeRubyChina#4]
2016-04-20 10:49:17.370 [trace][tid:com.facebook.React.JavaScript][RCTJSCProfiler.m:63] JSC profiler is not supported.
2016-04-20 10:49:17.533 [error][tid:main] Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate

URL: http://localhost:8081/index.ios.bundle?platform=ios&dev=true
2016-04-20 10:49:34.553 [error][tid:main] Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate

URL: http://localhost:8081/index.ios.bundle?platform=ios&dev=true
2016-04-20 10:49:35.776 [error][tid:main] Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate

URL: http://localhost:8081/index.ios.bundle?platform=ios&dev=true

**Comment by zp0708** [comment]
- To run on device, change `localhost` to the IP address of your computer
- (you can get this by typing `ifconfig` into the terminal and selecting the
- `inet` value under `en0:`) and make sure your computer and iOS device are
- on the same Wi-Fi network.

**Comment by henter** [comment]
@NewUnsigned 网络问题？

**Comment by zp0708** [comment]
每配置好，问题已解决 ，谢啦
